# probably youre looking for pkg/deej/scripts/misc/default-config.yaml ?
invert_sliders: false
slider_mapping:
  0:
  1:
  2:
  3:
  4:
  5:

slider_override:
  0: 
  1:
  2:
  3:
  4:
  5:

invert_switches: false
switches_mapping:
  0: 
  1:
  2:
  3:
  4:
  5:


SERIAL_Port: COM18
SERIAL_BaudRate: 115200
SSE_URL: http://mix.local/events
#SSE_RELAY_PORT: 8080